[2025-01-16 19:37:46,380] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-01T00:00:00+00:00 [queued]>
[2025-01-16 19:37:46,386] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-01T00:00:00+00:00 [queued]>
[2025-01-16 19:37:46,386] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2025-01-16 19:37:46,386] {taskinstance.py:1096} INFO - Starting attempt 3 of 4
[2025-01-16 19:37:46,386] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2025-01-16 19:37:46,396] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2016-12-01T00:00:00+00:00
[2025-01-16 19:37:46,398] {standard_task_runner.py:52} INFO - Started process 312686 to run task
[2025-01-16 19:37:46,402] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', '2016-12-01T00:00:00+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmprsg2ghs8', '--error-file', '/tmp/tmpe5pskg_j']
[2025-01-16 19:37:46,402] {standard_task_runner.py:77} INFO - Job 10: Subtask pyspark_train_classifier_model
[2025-01-16 19:37:46,424] {logging_mixin.py:109} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-01T00:00:00+00:00 [running]> on host ibdn-VirtualBox
[2025-01-16 19:37:46,445] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2016-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-12-01T00:00:00+00:00
[2025-01-16 19:37:46,446] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-01-16 19:37:46,446] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nspark-submit --master local[8]   /home/ibdn/BDFI/practica_creativa//resources/train_spark_mllib_model.py   /home/ibdn/BDFI/practica_creativa/']
[2025-01-16 19:37:46,456] {subprocess.py:74} INFO - Output:
[2025-01-16 19:37:48,207] {subprocess.py:78} INFO - 25/01/16 19:37:48 WARN Utils: Your hostname, ibdn-VirtualBox resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2025-01-16 19:37:48,220] {subprocess.py:78} INFO - 25/01/16 19:37:48 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-01-16 19:37:49,180] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO SparkContext: Running Spark version 3.3.0
[2025-01-16 19:37:49,335] {subprocess.py:78} INFO - 25/01/16 19:37:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-16 19:37:49,490] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO ResourceUtils: ==============================================================
[2025-01-16 19:37:49,493] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-01-16 19:37:49,493] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO ResourceUtils: ==============================================================
[2025-01-16 19:37:49,493] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO SparkContext: Submitted application: train_spark_mllib_model.py
[2025-01-16 19:37:49,545] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-01-16 19:37:49,557] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO ResourceProfile: Limiting resource is cpu
[2025-01-16 19:37:49,558] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-01-16 19:37:49,645] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO SecurityManager: Changing view acls to: ibdn
[2025-01-16 19:37:49,646] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO SecurityManager: Changing modify acls to: ibdn
[2025-01-16 19:37:49,647] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO SecurityManager: Changing view acls groups to:
[2025-01-16 19:37:49,648] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO SecurityManager: Changing modify acls groups to:
[2025-01-16 19:37:49,648] {subprocess.py:78} INFO - 25/01/16 19:37:49 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ibdn); groups with view permissions: Set(); users  with modify permissions: Set(ibdn); groups with modify permissions: Set()
[2025-01-16 19:37:50,059] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO Utils: Successfully started service 'sparkDriver' on port 38731.
[2025-01-16 19:37:50,113] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO SparkEnv: Registering MapOutputTracker
[2025-01-16 19:37:50,165] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO SparkEnv: Registering BlockManagerMaster
[2025-01-16 19:37:50,247] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-01-16 19:37:50,248] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-01-16 19:37:50,259] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-01-16 19:37:50,306] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-67e1ac98-cf6e-4895-9c95-776901bcebc6
[2025-01-16 19:37:50,340] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-01-16 19:37:50,362] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-01-16 19:37:50,844] {subprocess.py:78} INFO - 25/01/16 19:37:50 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-01-16 19:37:51,080] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO Executor: Starting executor ID driver on host 10.0.2.15
[2025-01-16 19:37:51,094] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-01-16 19:37:51,141] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41751.
[2025-01-16 19:37:51,141] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO NettyBlockTransferService: Server created on 10.0.2.15:41751
[2025-01-16 19:37:51,144] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-01-16 19:37:51,162] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.2.15, 41751, None)
[2025-01-16 19:37:51,171] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO BlockManagerMasterEndpoint: Registering block manager 10.0.2.15:41751 with 434.4 MiB RAM, BlockManagerId(driver, 10.0.2.15, 41751, None)
[2025-01-16 19:37:51,189] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.2.15, 41751, None)
[2025-01-16 19:37:51,190] {subprocess.py:78} INFO - 25/01/16 19:37:51 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.2.15, 41751, None)
[2025-01-16 19:37:51,455] {local_task_job.py:204} WARNING - Recorded pid 312781 does not match the current pid 312686
[2025-01-16 19:37:51,471] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 312686
[2025-01-16 19:37:51,472] {taskinstance.py:1236} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-16 19:37:51,472] {subprocess.py:88} INFO - Sending SIGTERM signal to process group
[2025-01-16 19:37:51,476] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 171, in execute
    output_encoding=self.output_encoding,
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 76, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1238, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-16 19:37:51,489] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20161201T000000, start_date=20250116T183749, end_date=20250116T183751
[2025-01-16 19:37:51,563] {process_utils.py:66} INFO - Process psutil.Process(pid=312686, status='terminated', exitcode=1, started='19:37:46') (312686) terminated with exit code 1
[2025-01-16 19:37:51,563] {process_utils.py:66} INFO - Process psutil.Process(pid=312770, status='terminated', started='19:37:48') (312770) terminated with exit code None
[2025-01-16 19:37:51,844] {process_utils.py:66} INFO - Process psutil.Process(pid=312687, status='terminated', started='19:37:46') (312687) terminated with exit code None
